### PR TITLE
Openstack info

### PR DESCRIPTION
**Pull request by son-vyas**
Please do review and suggest the changes if any.

### CODE REVIEW

**Comment by akshaygin** [comment]
@son-vyas Some changes:
- Many time you have written Openstack. It should be OpenStack. Also Infrastructure-as-a-provider
- open source or open-source is correct instead of opensource.
- I think we should write in OpenStack releases section along with link for releases. (without including table of releases). Adding about release naming or release cycle in short would be better. What do you think?

**Comment by son-vyas** [comment]
I don't really think there is any need to mention about release naming or cycle, since the link will explain everything.

**Comment by KhushbuB** [comment]
Can you please make the changes of word "openstack" to "OpenStack".

**Comment by KhushbuB** [comment]
Good to go.

**Pull request merged**
