### PR TITLE
chapter2 readme

### PR DESCRIPTION
**Pull request by son-vyas**

### CODE REVIEW

**Review by KhushbuB — COMMENTED** [review]
Good. You may also add a short description of the sub chapters as it was done for chapter 1.

**Review by KhushbuB — DISMISSED** [review]
Everything is good just follow the sequence of sub chapters as per Chapter Structure so it would be easier for the reader to refer.

**Comment by son-vyas** [comment]
Will you specify exactly where the sequence goes wrong, because according to me , it is fine.

**Comment by akshaygin** [comment]
@son-vyas Good. Sequence is correct now.

**Pull request merged**
